name: Python package

on: 
    push:
        tags:
            - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: install lib
      run: pip install -r require.txt

    - name: run script
      run: python public_apk.py
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        ASSETS: "./require.txt ./README.md"
        REPOSITORY: anantasak-pcru/python_upload_release_assets