name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: install lib
      run: pip install -r require.txt

    - name: run script
      run: python public_apk.py
      env:
        BODY: ${{ github.event.head_commit.message }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ASSETS: "/require.txt /README.md"
        REPOSITORY: anantasak/actions_generate_changelog_test